version: 2.1

executors:
  java:
    parameters:
      tag:
        type: string
        default: 12-jdk-hotspot
    docker:
      - image: 377069709311.dkr.ecr.us-east-1.amazonaws.com/base_ci_build:<< parameters.tag >>
        aws_auth:
          aws_access_key_id: $ECR_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY
    working_directory: ~/repo
    environment:
      PROJECT_NAME: zookeeper
      SLACK_NOTIFY_CHANNEL: "#log-ingestion-notify"
      EMOJI: ":circle-pass:"

commands:
  cacheit:
    steps:
      - run:
          name: generate cache checksum
          command: find . -name pom.xml | sort | xargs -n 1 cat > /tmp/maven_cached_poms
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "/tmp/maven_cached_poms" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: mvn -q -s .circleci/m2/settings.xml test-compile
      - save_cache:
          paths:
            - ~/.m2/repository
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "/tmp/maven_cached_poms" }}

jobs:
  build:
    executor: java
    steps:
      - checkout
      - cacheit

  deploy:
    executor: java
    steps:
      - checkout
      - cacheit
      - run:
          name: Deploy snapshot
          command: |
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            BRANCH=$(echo -n "${CIRCLE_BRANCH}" | sed -e 's/[^0-9a-zA-Z\._\-]/./g' | tr '[:upper:]' '[:lower:]')
            NEW_VERSION=${VERSION%%-SNAPSHOT}-$BRANCH-SNAPSHOT
            mvn versions:set -DnewVersion=$NEW_VERSION

            mvn -s .circleci/m2/settings.xml package -DskipTests

            mvn -s .circleci/m2/settings.xml deploy:deploy-file -DgroupId=org.apache.zookeeper \
              -DartifactId=zookeeper-parent \
              -Dversion=$NEW_VERSION \
              -Dpackaging=pom \
              -Dfile=pom.xml \
              -DrepositoryId=github \
              -Durl=https://maven.pkg.github.com/solarwindscloud/maven-releases
            mvn -s .circleci/m2/settings.xml deploy:deploy-file -DgroupId=org.apache.zookeeper \
              -DartifactId=zookeeper \
              -Dversion=$NEW_VERSION \
              -Dpackaging=jar \
              -DpomFile=zookeeper/pom.xml \
              -Dfile=zookeeper/target/zookeeper-$NEW_VERSION.jar \
              -DrepositoryId=github \
              -Durl=https://maven.pkg.github.com/solarwindscloud/maven-releases

            source /ci-scripts/bin/helpers.sh
            send_to_slack "A new snapshot is ready \`$NEW_VERSION\`"

  release:
    executor: java

    steps:
      - checkout
      - cacheit
      - run:
          name: Check versions
          command: mvn versions:use-releases
      - run:
          name: Configure git for release
          command: |
            git config user.name "librato-ci"
            git config user.email "tools+librato-ci-githublibrato.com"
      - run:
          name: Perform release
          command: |
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed s/-SNAPSHOT//)
            mvn versions:set -DnewVersion=$VERSION versions:commit

            mvn -s .circleci/m2/settings.xml package -DskipTests

            mvn -s .circleci/m2/settings.xml deploy:deploy-file -DgroupId=org.apache.zookeeper \
              -DartifactId=zookeeper-parent \
              -Dversion=$VERSION \
              -Dpackaging=pom \
              -Dfile=pom.xml \
              -DrepositoryId=github \
              -Durl=https://maven.pkg.github.com/solarwindscloud/maven-releases
            mvn -s .circleci/m2/settings.xml deploy:deploy-file -DgroupId=org.apache.zookeeper \
              -DartifactId=zookeeper \
              -Dversion=$VERSION \
              -Dpackaging=jar \
              -DpomFile=zookeeper/pom.xml \
              -Dfile=zookeeper/target/zookeeper-$VERSION.jar \
              -DrepositoryId=github \
              -Durl=https://maven.pkg.github.com/solarwindscloud/maven-releases

            source /ci-scripts/bin/helpers.sh
            send_to_slack "A new release is ready \`$VERSION\`"

workflows:
  version: 2
  build_test_release:
    jobs:
      - build:
          context:
            - AWS_CIRCLE_CI_BUILD
            - GH_LIBRATO_CI_PKG_READ
            - WHITESOURCE
          filters:
            branches:
              # Note this will need to be updated any time we need to branch again!
              only:
                - branch-3.4.14-swi
      - deploy:
          context:
            - AWS_CIRCLE_CI_BUILD
            - GH_LIBRATO_CI_PKG_READ
            - GH_LIBRATO_CI_PKG_WRITE
            - SLACK_HOOK
          requires:
            - build
          filters:
            branches:
              # Note this will need to be updated any time we need to branch again!
              only: SP-2583_name_resolver_fix_2
      - release:
          context:
            - AWS_CIRCLE_CI_BUILD
            - GH_LIBRATO_CI_PKG_READ
            - GH_LIBRATO_CI_PKG_WRITE
            - SLACK_HOOK
          requires:
            - build
          filters:
            branches:
              only: branch-3.4.14-swi
